platform :ios, '15.0'

target 'anime_character_identifier_app' do
  use_frameworks!

  # AWS SDK
  pod 'AWSS3'
  
  # Testing
  target 'anime_character_identifier_appTests' do
    inherit! :search_paths
  end

  target 'anime_character_identifier_appUITests' do
    inherit! :search_paths
  end
end 